import { getFirestore } from '../lib/firestore.js';
import axios from 'axios';

export async function detectGameweek(): Promise<{ gwId: number; deadlineTime: string }> {
  try {
    const res = await axios.get('https://fantasy.premierleague.com/api/bootstrap-static/', {
      headers: { 'User-Agent': 'Mozilla/5.0' }
    });
    const data = res.data;
    const nextEvent = data.events?.find((e: any) => e.is_next) ??
                      data.events?.find((e: any) => new Date(e.deadline_time) > new Date());
    if (nextEvent?.id) {
      return { gwId: nextEvent.id, deadlineTime: nextEvent.deadline_time };
    }
  } catch (err: any) {
    console.warn(`[AutoSnapshot] FPL API bootstrap error: ${err.message}`);
  }
  return { gwId: 1, deadlineTime: new Date().toISOString() };
}

export async function runAutoSnapshots(overrideGwId?: number) {
  console.log("🚀 [AutoSnapshot] Starting Pre-Deadline Automated Cloud Snapshots...");

  const db = getFirestore();
  if (!db) {
    console.warn("⚠️ [AutoSnapshot] Could not initialize Firestore. Check GOOGLE_CLOUD_* environment variables.");
    return;
  }

  const { gwId: detectedGwId, deadlineTime } = await detectGameweek();
  const gwId = overrideGwId || detectedGwId;
  console.log(`📌 [AutoSnapshot] Targeting Gameweek ${gwId} (Deadline: ${deadlineTime})`);

  // Default team IDs to guarantee tracking for core accounts
  const defaultTeamIds = ['532002', '1884833', '3097103', '902458', '904491', '601847', '906422', '1921923', '1924837', '600311', '3274378', '9291073', '903137'];

  let teamIdList: string[] = [...defaultTeamIds];

  try {
    const snapshotDocs = await db.collection('user_snapshots').get();
    snapshotDocs.forEach(doc => {
      if (doc.id.startsWith('team_')) {
        const tid = doc.id.replace('team_', '').trim();
        if (tid && !teamIdList.includes(tid)) {
          teamIdList.push(tid);
        }
      }
    });
  } catch (err: any) {
    console.warn("[AutoSnapshot] Notice fetching Firestore team documents:", err.message);
  }

  console.log(`📋 [AutoSnapshot] Found ${teamIdList.length} teams to snapshot:`, teamIdList);

  const fuels: ('fplform' | 'native' | 'eye-test')[] = ['fplform', 'native', 'eye-test'];
  const modes: ('safe' | 'aggressive' | 'value')[] = ['safe', 'aggressive', 'value'];
  const scenarios: ('quant' | 'template')[] = ['quant', 'template'];

  let successCount = 0;

  for (const tid of teamIdList) {
    const docKey = `team_${tid}`;
    try {
      const docRef = db.collection('user_snapshots').doc(docKey);
      const docSnap = await docRef.get();
      const existingHistory = docSnap.exists ? (docSnap.data()?.history || {}) : {};

      const newGwHistory = { ...(existingHistory[gwId] || {}) };

      for (const fuel of fuels) {
        for (const scenario of scenarios) {
          for (const mode of modes) {
            const snapshotKey = `${fuel}_${scenario}_${mode}`;
            
            const snapshotItem = {
              key: snapshotKey,
              fuel,
              scenario,
              riskMode: mode,
              fuelLabel: fuel === 'eye-test' ? 'Eye Test' : fuel === 'native' ? 'Native FPL' : 'FPLForm',
              scenarioLabel: scenario === 'quant' ? 'Quant Optimal' : 'Risky Template Shield',
              riskLabel: mode.toUpperCase(),
              autoGenerated: true,
              timestamp: Date.now()
            };

            newGwHistory[snapshotKey] = snapshotItem;
            newGwHistory[mode] = snapshotItem;
          }
        }
      }

      existingHistory[gwId] = newGwHistory;

      await docRef.set({
        history: existingHistory,
        season: '2026/27',
        lastAutoSnapshotAt: new Date()
      }, { merge: true });

      successCount++;
      console.log(`✅ [AutoSnapshot] Saved GW${gwId} snapshots for team ${tid}`);
    } catch (err: any) {
      console.error(`❌ [AutoSnapshot] Error saving snapshots for team ${tid}:`, err.message);
    }
  }

  console.log(`🎉 [AutoSnapshot] Completed! Saved snapshots for ${successCount}/${teamIdList.length} teams for GW${gwId}.`);
}

// Execute if called directly from CLI
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('auto-snapshot.ts')) {
  runAutoSnapshots();
}
